services:
  postgres:
    image: postgres:16-alpine
    container_name: vinfast-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vinfast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - vinfast_postgres_data:/var/lib/postgresql/data

volumes:
  vinfast_postgres_data:

